git :
  commit : '@git.commit.id.abbrev@'
  build_time : '@git.build.time@'

info :
  app :
    name : '@project.name@'
    description : '@project.description@'
    version : '@project.version@'
    git_commit : ${git.commit}
    build_time : ${git.build_time}

spring :
  application :
    name : quickstart-amqp-consuming-hello
  jackson :
    default-property-inclusion : NON_NULL
  lifecycle :
    timeout-per-shutdown-phase : ${TIMEOUT_PER_SHUTDOWN:20s}
  rabbitmq :
    host : ${RABBITMQ_HOST:localhost}
    port : ${RABBITMQ_PORT:5672}
    username : ${RABBITMQ_USERNAME:svc_testing}
    password : ${RABBITMQ_PASSWORD:svc_testing}
  devtools :
    add-properties : false
    restart :
      enabled : false
    livereload :
      enabled : false
logging :
  pattern :
    level : '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level :
    ROOT : ${LOGGING_LEVEL_ROOT:INFO}

management :
  info :
    env :
      enabled : true
    java :
      enabled : true
    os :
      enabled : true
  health :
    livenessstate :
      enabled : true
    readinessstate :
      enabled : true
  server :
    port : ${MANAGEMENT_SERVER_PORT:8080}
    add-application-context-header : true

  metrics :
    tags :
      application : ${spring.application.name}
      profiles : ${spring.profiles.active}
    distribution :
      percentiles-histogram :
        http :
          server :
            requests : true
  tracing :
    sampling :
      probability : 1.0
    enabled : true
  prometheus :
    metrics :
      export :
        step : 20s
        enabled : true
  zipkin :
    tracing :
      endpoint : ${TEMPO_URL:http://localhost:9411/api/v2/spans}


  endpoints :
    enabled-by-default : false
    web :
      exposure :
        include : health, metrics, prometheus, info, env
  endpoint :
    health :
      enabled : true
      show-details : always
      probes :
        enabled : true
    info :
      enabled : true
    env :
      enabled : true
      show-values : always
    prometheus :
      enabled : true

server :
  port : ${SERVER_PORT:8080}
  shutdown : graceful
  forward-headers-strategy : framework
  tomcat :
    redirect-context-root : false

embedded :
  rabbitmq :
    enabled : false
    reuse-container : true

iqkv :
  build :
    description : '@project.description@'
    relative-path : ${SERVER_SERVLET_CONTEXT_PATH:/}
    version : '@project.version@'
  amqp :
    queues :
      greeter-exchange : ${AMQP_GREETER_EXCHANGE:greeter-exchange}
      greeter-queue : ${AMQP_GREETER_QUEUE:greeter-queue}
