git :
  commit : '@git.commit.id.abbrev@'
  build_time : '@git.build.time@'

info :
  app :
    name : '@project.name@'
    description : '@project.description@'
    version : '@project.version@'
    git_commit : ${git.commit}
    build_time : ${git.build_time}

spring :
  application :
    name : quickstart-amqp-consuming-hello
  jackson :
    default-property-inclusion : NON_NULL
  lifecycle :
    timeout-per-shutdown-phase : ${TIMEOUT_PER_SHUTDOWN:20s}
  rabbitmq :
    host : ${RABBITMQ_HOST:localhost}
    port : ${RABBITMQ_PORT:5672}
    username : ${RABBITMQ_USERNAME:sa_test}
    password : ${RABBITMQ_PASSWORD:sa_test}
  devtools :
    add-properties : false
    restart :
      enabled : false
    livereload :
      enabled : false
logging :
  level :
    ROOT : ${LOGGING_LEVEL_ROOT:INFO}

management :
  info :
    env :
      enabled : true
  health :
    livenessstate :
      enabled : true
    readinessstate :
      enabled : true
  server :
    add-application-context-header : true
  endpoints :
    enabled-by-default : false
    web :
      exposure :
        include : health, prometheus, info
  endpoint :
    health :
      enabled : true
      show-details : always
      probes :
        enabled : true
    info :
      enabled : true
    prometheus :
      enabled : true

server :
  port : ${SERVER_PORT:8080}
  shutdown : graceful

embedded :
  rabbitmq :
    enabled : false
    reuse-container : true

ujar :
  build :
    description : '@project.description@'
    relative-path : ${SWAGGER_UI_RELATIVE_PATH:}
    version : '@project.version@'
  amqp :
    queues :
      greeter-exchange : ${AMQP_GREETER_EXCHANGE:greeter-exchange}
      greeter-queue : ${AMQP_GREETER_QUEUE:greeter-queue}
