spring:
  devtools :
    add-properties : true
    restart :
      enabled : true
    livereload :
      enabled : true
management :
  endpoints :
    enabled-by-default : true

ujar :
  amqp:
    queues :
      greeter-exchange: greeter-exchange
      greeter-queue: greeter-queue
